logging:
    level:
        com:
            god:
                bo:
                    test: info
                    test.controller: info
        root: info
mybatis:
    configuration:
        jdbc-type-for-null: 'null'
        map-underscore-to-camel-case: true
    mapper-locations: classpath:/mapper/**/**/sqlMap*.xml
    type-aliases-package: kr.co.seoulit.logistics
resource:
    location: C:/Users/tmdgu/Downloads/????/???? ????/75? ??????/03. Project File/logi_back
server:
    port: 9090
    tomcat:
        additional-tld-skip-patterns: '*.jar'
spring:
    datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        password: nexalogi765
        url: jdbc:log4jdbc:oracle:thin:@//localhost:1521/xe
        username: nexalogi765
    main:
        allow-bean-definition-overriding: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    servlet:
        multipart:
            maxFileSize: 10MB
            maxRequestSize: 10MB
tomcat:
    ajp:
        enabled: true
        port: 8009
        protocol: AJP/1.3
        remoteauthentication: false
